name: .NET Core

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 7.0.x
            - name: Install dependencies
              run: dotnet restore
              working-directory: ./src/MineCosmos.Buffers/
            - name: Build
              run: dotnet build --configuration Release --no-restore
              working-directory: ./src/MineCosmos.Buffers/
            - name: Test
              run: dotnet test --no-restore --verbosity normal
            - name: Publish
              uses: brandedoutcast/publish-nuget@v2.5.2
              with:
                  PROJECT_FILE_PATH: src/MineCosmos.Buffers/MineCosmos.Buffers.csproj
                  NUGET_KEY: ${{secrets.NUGET}}
